services:
  ultraviolet:
    build:
      context: .
    container_name: ultraviolet
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8080
    expose:
      - "8080"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
